### ISSUE TITLE
please introduce folder for checkers project

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#1]
This repository will hold multiple _**projects**_ throughout the rest of the course. It's important that each project has it's own dedicated folder. 

Please create a folder "checkers" and place your source code within there.

**ALSO** please rename `checkers.html` to `index.html`

**Comment by AllusionMack** [comment]
@WaterBuffaloTM I see you haven't renamed to index.html

**Comment by WaterBuffaloTM** [comment]
finished
