### ISSUE TITLE
missing closing tag for <ul>

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#11]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/eebd718051c867b3036b8403a74c5ff880a07834/contact_manager/createAContact/Index.Html%20.html#L19

There's no associated closing for the `<ul>`, the result is invalid HTML.

**Comment by WaterBuffaloTM** [comment]
will check my new code but dont believe I made this mistake
