### ISSUE TITLE
there's also no <li> closing tag

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#12]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/eebd718051c867b3036b8403a74c5ff880a07834/contact_manager/createAContact/Index.Html%20.html#L20

it looks like somewhere along the line, through error, the closing tag was removed for this `<li>` element as well.

**Comment by WaterBuffaloTM** [comment]
same as last comment
