### ISSUE TITLE
convert internal CSS to use external style sheet.

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#3]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/3bc970885b767c4756776f3285283ab1178a163e/checkers.html#L14

Instead of using internal CSS, lets get in the habit of using external style sheets. I see you've already created a style sheet.... `styles.css` but it's not referenced anywhere.

For a reminder on how to do this: https://www.w3schools.com/css/css_howto.asp

**Comment by AllusionMack** [comment]
@WaterBuffaloTM I noticed you haven't changed this yet. Is this on your radar?

**Comment by WaterBuffaloTM** [comment]
Finished
