### ISSUE TITLE
Contact Manager - Please rename folders and file names as per directions

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#4]
Please view the _**very specific**_ directions outlined here on the last page of the "Contact Manager" Frontend slides: https://floridafullstack.gitbook.io/cohort-1/activities/contact-manager

All of the folders and files were named incorrectly.

**Comment by WaterBuffaloTM** [comment]
old comment made corrections on new folder
