### ISSUE TITLE
remove capital D in Div

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#5]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/eebd718051c867b3036b8403a74c5ff880a07834/contact_manager/createAContact/Index.Html%20.html#L27

Additionally, there's an extra space in the `<h1>` text

**Comment by WaterBuffaloTM** [comment]
I am stupid but not that stupid
