### ISSUE TITLE
move script tag to bottom of body element

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#6]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/eebd718051c867b3036b8403a74c5ff880a07834/contact_manager/createAContact/Index.Html%20.html#L11

We want our script tags at the **bottom** of our _body_ element. The reason we do this is because we wish to load the entire DOM **_first_** and then load the javascript. 

Please read this: [https://stackoverflow.com/a/17140419](https://stackoverflow.com/a/17140419) 

Please move script tag to the bottom of body element.

**Comment by WaterBuffaloTM** [comment]
Made corrections during my new sheet
