### ISSUE TITLE
The container should be the outer div, with the form inside

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#7]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/eebd718051c867b3036b8403a74c5ff880a07834/contact_manager/createAContact/Index.Html%20.html#L30

So here I am noticing that you are placing a `<div class="container">` within a `<form>`. Please change it so the container is the parent element.

Generally, when introducing a `container` we view it as a separate and isolated section that contains a bunch of `row`s and `col`. I suggest going back and looking at some of the grid system examples on bootstrap.

Also, please look over the last few "Frontend" slides here: https://floridafullstack.gitbook.io/cohort-1/activities/contact-manager which contain links that you should be referenced when doing each page.

What I've noticed is that it's clear that you skipped over the last few slides of the assignment, which contained clear directions on the file structure as well as direct copy & paste links for you to work off of. 

Please do a better job ensuring that you are taking the time to read all of the course materials regarding assignments.

Also, I'm not seeing this `<div>`'s closing tag.

**Comment by WaterBuffaloTM** [comment]
Made sure to include the divs as parent elements to what was going inside (children)
