### ISSUE TITLE
remove active class

### ISSUE THREAD

**Issue by AllusionMack** [WaterBuffaloTM/matthew-nguyen-2#9]
https://github.com/WaterBuffaloTM/matthew-nguyen-2/blob/eebd718051c867b3036b8403a74c5ff880a07834/contact_manager/createAContact/Index.Html%20.html#L21

since we're not currently on the "view all contacts" page, the nav should not be displaying it as such. The `active` class is what styles this.

**Comment by WaterBuffaloTM** [comment]
did not make this mistake in new one
